### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by dcschaper**
Changed expected environment variable from $LEGEND_CONFIG to $LEGEND_DATA_CONFIG

### CODE REVIEW

**Comment by oschulz** [comment]
Sorry @dcschaper I overlooked this one. Could you resolve the merge conflicts?

**Comment by dcschaper** [comment]
@oschulz Done!

**Comment by dcschaper** [comment]
Although I think there might be a few other files in the docs that also refer to $LEGEND_CONFIG instead of $LEGEND_DATA_CONFIG -- might want to check these for consistency? I think the variable name that was settled on was $LEGEND_DATA_CONFIG instead of $LEGEND_CONFIG?

**Comment by oschulz** [comment]
Thanks - yes, there was one more instance of `LEGEND_CONFIG`, fixed that just now too. Now we just need to figure out what's wrong with the paths on Windows. :-)

**Pull request merged**
